name: Publish to GitHub Packages

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: 'github'
          server-username: 'GITHUB_ACTOR'
          server-password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          mvn -B versions:set -DnewVersion="$VERSION" -DgenerateBackupPoms=false

      - name: Build & Deploy
        run: mvn -B -DskipTests deploy
